"""add minimum_stock to products

Revision ID: 55431fa32957
Revises: 4435c60a903d
Create Date: 2026-09-19 23:04:11.484708

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '55431fa32957'
down_revision: Union[str, Sequence[str], None] = '4435c60a903d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('minimum_stock', sa.Integer(),server_default='5' ,nullable=True))
    # ### end Alembic commands ###
 

def downgrade() -> None: 
    pass